# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/RISC-V_RV32EM/RISC-V_RV32EM.cache/wt [current_project]
set_property parent.project_path C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/RISC-V_RV32EM/RISC-V_RV32EM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/RISC-V_RV32EM/RISC-V_RV32EM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/ALU.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/ALU_control.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/ALU_src.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/ALU_unit.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/pack.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/EX_MEM.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/ID_EX.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/IF_ID.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/MEM_WB.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/PC.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/branch.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/control_unit.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/data_memory.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/fowarding_unit.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/hasard_detection_unit.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/imm_gen.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/instruction_mem.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/registers.vhd
  C:/Users/Francis/OneDrive/Documents/ELE749-01/Laboratoires/Laboratoire_4/Integration_RISC/Datapath.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Datapath -part xc7a35tcpg236-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Datapath.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Datapath_utilization_synth.rpt -pb Datapath_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
